name: Deploy to Namecheap

on:
  push:
    branches:
      - main

jobs:
  deploy-client:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install lftp
        run: sudo apt-get install lftp -y

      - name: Deploy client to Namecheap
        env:
          FTP_SERVER: ${{ secrets.FTP_SERVER }}
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        run: |
          # Create a list of local files to be deployed
          cd client/
          find . -type f | grep -v "node_modules" > ../client_files.txt
          cd ..

          lftp -e "set ssl:verify-certificate no; \
          open ftp://$FTP_USERNAME:$FTP_PASSWORD@$FTP_SERVER; \
          cd app.berrysol.com/; \

          # For each local file, check if it exists on remote and delete if so
          cat client_files.txt | while read file; do \
            if [ -f \"$file\" ]; then \
              echo \"Checking if \$file exists on remote\"; \
              glob -a \"rm -f \$file\" || echo \"File \$file not present\"; \
            fi; \
          done; \

          # Upload client files, preserving node_modules if it exists
          lcd client/; \
          mirror -R --verbose --exclude-glob .git/ --exclude-glob .github/ --exclude-glob node_modules/ ./ ../app.berrysol.com/; \
          bye"

          rm client_files.txt

  deploy-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install lftp
        run: sudo apt-get install lftp -y

      - name: Deploy server to Namecheap
        env:
          FTP_SERVER: ${{ secrets.FTP_SERVER }}
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        run: |
          # Create a list of local files to be deployed
          cd server/
          find . -type f | grep -v "node_modules" > ../server_files.txt
          cd ..

          lftp -e "set ssl:verify-certificate no; \
          open ftp://$FTP_USERNAME:$FTP_PASSWORD@$FTP_SERVER; \
          cd testbackend.berrysol.com/; \

          # For each local file, check if it exists on remote and delete if so
          cat server_files.txt | while read file; do \
            if [ -f \"$file\" ]; then \
              echo \"Checking if \$file exists on remote\"; \
              glob -a \"rm -f \$file\" || echo \"File \$file not present\"; \
            fi; \
          done; \

          # Upload server files, preserving node_modules if it exists
          lcd server/; \
          mirror -R --verbose --exclude-glob .git/ --exclude-glob .github/ --exclude-glob node_modules/ ./ ../testbackend.berrysol.com/; \
          bye"

          rm server_files.txt
