name: Deploy to Namecheap

on:
  push:
    branches:
      - main

jobs:
  deploy-client:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install client dependencies
        run: |
          cd client
          npm ci

      - name: Build client
        run: |
          cd client
          npx vite build

      - name: Install lftp
        run: sudo apt-get install lftp -y

      - name: Deploy client to Namecheap
        env:
          FTP_SERVER: ${{ secrets.FTP_SERVER }}
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        run: |
          # Create a list of files in the dist directory
          cd client/dist/
          find . -type f > ../../client_dist_files.txt
          cd ../..

          lftp -e "set ssl:verify-certificate no; \
          open ftp://$FTP_USERNAME:$FTP_PASSWORD@$FTP_SERVER; \
          cd app.berrysol.com/; \

          # For each file in dist, check if it exists on remote and delete if so
          cat client_dist_files.txt | while read file; do \
            remotefile=\$(echo \$file | sed 's|^./||'); \
            echo \"Checking if \$remotefile exists on remote\"; \
            glob -a \"rm -f \$remotefile\" || echo \"File \$remotefile not present\"; \
          done; \

          # Upload all files from dist folder to root directory
          lcd client/dist/; \
          mirror -R --verbose --exclude-glob .git/ --exclude-glob .github/ ./ ../app.berrysol.com/; \
          bye"

          rm client_dist_files.txt

  deploy-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install lftp
        run: sudo apt-get install lftp -y

      - name: Deploy server to Namecheap
        env:
          FTP_SERVER: ${{ secrets.FTP_SERVER }}
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        run: |
          # Create a list of local files to be deployed
          cd server/
          find . -type f | grep -v "node_modules" > ../server_files.txt
          cd ..

          lftp -e "set ssl:verify-certificate no; \
          open ftp://$FTP_USERNAME:$FTP_PASSWORD@$FTP_SERVER; \
          cd testbackend.berrysol.com/; \

          # For each local file, check if it exists on remote and delete if so
          cat server_files.txt | while read file; do \
            remotefile=\$(echo \$file | sed 's|^./||'); \
            echo \"Checking if \$remotefile exists on remote\"; \
            glob -a \"rm -f \$remotefile\" || echo \"File \$remotefile not present\"; \
          done; \

          # Upload server files, preserving node_modules if it exists
          lcd server/; \
          mirror -R --verbose --exclude-glob .git/ --exclude-glob .github/ --exclude-glob node_modules/ ./ ../testbackend.berrysol.com/; \
          bye"

          rm server_files.txt
